server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

## 阿里云 OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com # 地域节点
      keyid: LTAI5tFNjjg1s5mtpxxx6Rxc4 # AccessKeyId
      keysecret: fZvVNtbU8pNfxxxas53jYXhMUVHOo8 # 密钥
      bucketname: edu-xiuxxx # bucket名字







